#define yy_create_buffer css_create_buffer
#define yy_delete_buffer css_delete_buffer
#define yy_scan_buffer css_scan_buffer
#define yy_scan_string css_scan_string
#define yy_scan_bytes css_scan_bytes
#define yy_flex_debug css_flex_debug
#define yy_init_buffer css_init_buffer
#define yy_flush_buffer css_flush_buffer
#define yy_load_buffer_state css_load_buffer_state
#define yy_switch_to_buffer css_switch_to_buffer
#define yyin cssin
#define yyleng cssleng
#define yylex csslex
#define yyout cssout
#define yyrestart cssrestart
#define yytext csstext

#line 19 "css_scanner.h"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
static yyconst short int yy_accept[203] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   27,   25,
       20,   20,   25,   25,   25,   16,   17,   25,   25,   25,
        8,   13,   25,   25,    4,    4,   18,   25,   19,    4,
       14,   25,   15,   25,   26,   20,    0,    6,    0,    7,
        0,    0,    0,    0,    8,    0,    9,    0,    8,   10,
        0,    0,    5,    0,   22,    4,    0,    0,    4,    4,
       24,   23,    0,    0,    7,    0,    0,    3,    0,    0,
       10,    0,   10,    0,    5,    0,    5,    4,   12,    4,
        4,    4,    0,    0,    0,    7,    7,    0,    0,    0,
        0,    0,   21,   10,   10,   10,    2,    5,    5,    5,

        4,    4,    0,   12,    4,   22,    0,    7,    0,    0,
        0,    0,    0,   21,   10,   10,   10,    0,    1,    5,
        5,    5,    4,   12,   12,    4,    0,    0,    0,    0,
       11,    0,    0,    7,    0,    0,   10,   10,    5,    5,
        4,   12,   12,    4,    0,    0,    0,    0,    0,    0,
        0,    0,    7,    0,   10,   10,    5,    5,    4,   12,
       12,    4,    0,    0,    0,    0,    0,    0,    0,    0,
        7,    0,   10,   10,    5,    5,    4,   12,   12,    0,
        0,    0,    0,    0,    0,    0,   10,    5,   12,    0,
        0,    0,   12,    0,    0,    0,    0,    0,    0,    0,

        0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    6,    7,    8,    9,   10,    9,   11,   12,
       13,   14,   15,    9,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    9,   20,   21,
       22,   23,   24,   25,   26,   26,   26,   26,   26,   26,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   28,   27,   27,   27,   27,   27,
       29,   30,   31,    9,    9,    9,   32,   32,   32,   32,

       32,   32,   33,   33,   33,   33,   33,   34,   33,   33,
       33,   33,   33,   35,   33,   33,   36,   33,   33,   33,
       33,   33,   37,   38,   39,   40,    1,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,

       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    2,    3,    3,    3,    2,    2,    2,    2,    4,
        2,    5,    2,    2,    2,    6,    4,    2,    7,    2,
        2,    2,    2,    2,    2,    8,    8,    8,    2,    9,
        2,    9,    9,    9,    9,    9,    2,    2,    2,    2,
        9
    } ;

static yyconst short int yy_base[220] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  497,  692,
       40,   44,   43,  466,   40,  692,  692,  479,  474,  476,
       42,  692,  480,  444,   41,   45,  692,   35,  692,   41,
      692,  443,  692,  438,  692,   60,   48,  692,   76,  425,
       50,   47,  106,  421,   74,  414,  692,  395,   49,  368,
       55,  380,  309,   66,  692,  321,   67,   70,  137,   73,
      692,  692,   94,  168,  199,   89,  239,  692,  321,   98,
      304,   71,  270,  317,  301,   83,  310,  118,  127,  272,
       86,  114,  124,  125,   95,  221,  115,  119,  133,  116,
      223,  143,  692,  162,  189,  126,  202,  174,  158,  163,

      165,  164,  165,  173,  188,  350,  189,  190,  191,  160,
      172,  154,  198,  146,  129,  192,  194,  130,  692,   98,
      195,  198,  206,  220,  229,  217,  379,  257,  155,  217,
      692,  408,  233,  235,  238,  262,  247,  258,  259,  262,
      263,  237,  301,  264,  305,  286,  319,  438,  308,  468,
      345,  265,  266,  269,  309,  337,  339,  340,  341,  273,
      369,  343,  363,  367,  499,  376,  530,  359,  397,  375,
      418,  385,  386,  428,  405,  447,  406,  311,   97,  396,
      429,  415,  378,  424,  434,  459,  437,  448,  420,  456,
      457,  480,  692,  462,  473,  505,  494,  495,  540,  496,

      498,  692,  572,  580,  584,  592,  598,  600,  605,  614,
      618,  622,  631,  640,  649,  658,  666,  674,  682
    } ;

static yyconst short int yy_def[220] =
    {   0,
      202,    1,  203,  203,  203,  203,  203,  203,  202,  202,
      202,  202,  204,  205,  206,  202,  202,  202,  202,  202,
      207,  202,  202,  208,  209,  209,  202,  202,  202,   26,
      202,  202,  202,  202,  202,  202,  204,  202,  204,  205,
      202,  206,  206,  202,  207,  210,  202,  202,   45,  211,
      202,  202,  212,  202,  202,   26,  202,  202,   26,   26,
      202,  202,  204,  204,  202,  206,  206,  202,  210,  213,
      211,  202,  202,  202,  212,  202,  202,   59,  202,   26,
       59,   26,  204,  204,   64,  205,   65,  206,  206,   67,
      214,  215,  202,   73,  211,   73,  216,   77,  212,   77,

       26,   78,  202,  202,   59,  217,   64,   65,   67,  214,
      213,  214,  215,  214,  211,   94,   73,  216,  202,  212,
       98,   77,   78,  202,  202,   59,  217,  127,  218,  219,
      202,  127,   64,   65,   67,  215,   94,   73,   98,   77,
       78,  202,  202,   59,  202,  218,  202,  218,  219,  219,
      132,   64,   65,   67,   94,   73,   98,   77,   78,  202,
      202,   59,  202,  218,  218,  219,  219,  132,  132,   64,
      205,   67,   94,  211,   98,  212,   78,  202,  202,  218,
      218,  165,  219,  219,  167,  132,   94,   98,  202,  165,
      167,  132,  202,  165,  167,  132,  165,  167,  132,  165,

      167,    0,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202
    } ;

static yyconst short int yy_nxt[734] =
    {   0,
       10,   11,   12,   11,   11,   10,   13,   14,   10,   10,
       15,   16,   17,   10,   10,   18,   19,   20,   21,   22,
       23,   10,   10,   10,   24,   25,   25,   26,   27,   28,
       29,   25,   25,   25,   25,   30,   31,   32,   33,   34,
       25,   36,   36,   36,   36,   36,   36,   36,   36,   38,
       38,   47,   55,   59,   38,  202,   55,   38,   48,   58,
       49,   36,   36,   36,   36,   48,   59,   49,   65,   43,
       57,   51,   39,   73,   57,   60,   43,   39,   37,   37,
       63,   65,   38,   47,   77,   78,   73,  202,   79,   94,
      202,   42,   45,   79,   64,   79,   37,   77,   78,   38,

       38,   98,   94,   51,  105,   39,   82,   64,   42,   42,
       66,   92,  103,  107,   98,   93,   38,  105,   43,  101,
      101,  101,  101,   39,   67,  106,  107,   76,  202,   38,
       38,   38,  119,  108,  109,   43,  102,   67,   80,   80,
       80,   80,  103,   38,  117,  104,  108,  109,   43,  102,
      104,  202,  104,   39,   39,   81,  113,  117,   72,  111,
      114,  147,   43,  115,  115,  115,  115,  111,   81,   83,
       84,   84,   84,  111,   38,  120,  120,  120,  120,  202,
      116,  122,  123,  124,  148,  136,   85,   76,  103,   93,
      124,  125,  121,  116,  122,  123,  125,   39,  125,   85,

       86,   86,   86,   86,  119,  121,  126,  133,  134,  135,
      137,  113,  138,  139,   40,  114,  140,   87,   72,  126,
      133,  134,  135,  137,  141,  138,  139,  147,   41,  140,
       87,   40,   40,   40,   40,  144,  111,  141,  142,   40,
       88,   89,   89,   89,  103,  142,  150,  143,  144,   38,
       41,  152,  143,  153,  143,  160,  154,   90,  145,  145,
      145,  145,  160,  202,  152,  155,  153,  202,   43,  154,
       90,   95,   95,   95,   95,  136,  156,  157,  155,  114,
      158,  159,  162,  170,  171,   71,  202,  172,   96,  156,
      157,  178,  147,  158,  159,  162,  170,  171,  178,   72,

      172,   96,   71,   71,   71,   71,  145,  145,  145,  145,
       71,   99,   99,   99,   99,  148,  103,  131,  147,  161,
      163,  163,  163,  163,  161,   75,  161,  173,  100,  189,
       76,  131,   97,   72,   70,  202,  189,  150,   76,   76,
      173,  100,   75,   75,   75,   75,  168,  168,  168,  168,
       75,  127,  127,  127,  127,  174,  129,  175,  176,  177,
      130,   56,  131,  169,  163,  163,  163,  163,  174,  146,
      175,  176,  177,  147,   56,  131,  169,  128,  149,  132,
      127,  127,  127,  127,  103,  129,  147,  179,  147,  130,
      128,  131,  179,   37,  179,   74,  148,   72,  168,  168,

      168,  168,  147,   42,  187,  150,   37,  150,  132,  145,
      145,  145,  145,   45,  202,  186,   42,  187,  202,   86,
       86,   86,   86,  188,   56,  148,  151,   70,  186,   95,
       95,   95,   95,  190,  147,  147,  188,   56,  193,  151,
      146,  146,  164,   68,  147,  193,  190,   41,   99,   99,
       99,   99,  191,  150,   41,   71,  165,   72,  148,   62,
      168,  168,  168,  168,   61,  191,   75,  148,   71,  165,
      149,  149,  166,   54,  194,  195,   76,  192,  147,   75,
      197,  168,  168,  168,  168,   52,  167,  194,  195,   46,
      192,  198,   45,  197,   44,   41,  202,  150,  196,  167,

      180,  181,  181,  181,  198,  147,  168,  168,  168,  168,
      202,  196,  200,  201,  146,  202,  149,  182,  202,  202,
      202,  202,  202,  199,  202,  200,  201,  146,  148,  149,
      182,  183,  184,  184,  184,  202,  199,  202,  202,  202,
      147,  168,  168,  168,  168,  202,  202,  202,  185,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  128,  150,
      202,  185,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  128,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   37,  202,   37,   37,   37,   37,   37,   37,   40,
       40,  202,   40,   42,  202,   42,   42,   42,   42,   42,

       42,   50,  202,  202,   50,   50,   50,   53,   53,   56,
       56,   56,  202,   56,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   71,   71,  202,   71,   75,   75,  202,
       75,   91,   91,   91,   91,   91,   91,   91,   91,   91,
      110,  110,  110,  110,  110,  110,  110,  110,  110,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  128,  128,  128,
      202,  128,  128,  128,  128,  146,  202,  146,  146,  146,
      146,  146,  146,  149,  202,  149,  149,  149,  149,  149,
      149,    9,  202,  202,  202,  202,  202,  202,  202,  202,

      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202
    } ;

static yyconst short int yy_chk[734] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   11,   11,   11,   11,   12,   12,   12,   12,   13,
       15,   21,   25,   28,   37,   30,   26,   42,   21,   26,
       21,   36,   36,   36,   36,   49,   28,   49,   41,   15,
       25,   21,   13,   51,   26,   30,   42,   37,   39,   39,
       39,   41,   39,   45,   54,   57,   51,   60,   58,   72,
       45,   66,   45,   58,   39,   58,   63,   54,   57,   66,

       63,   76,   72,   45,   81,   39,   60,   39,   43,   43,
       43,   70,  179,   85,   76,   70,   43,   81,   66,   78,
       78,   78,   78,   63,   43,   82,   85,  120,   82,   88,
       83,   84,  118,   87,   90,   43,   78,   43,   59,   59,
       59,   59,   79,   89,   96,   79,   87,   90,   88,   78,
       79,   59,   79,   83,   84,   59,   92,   96,  115,  114,
       92,  129,   89,   94,   94,   94,   94,  112,   59,   64,
       64,   64,   64,  110,   64,   98,   98,   98,   98,  101,
       94,  100,  102,  103,  129,  111,   64,   99,  104,  111,
      103,  104,   98,   94,  100,  102,  104,   64,  104,   64,

       65,   65,   65,   65,   97,   98,  105,  107,  108,  109,
      116,  113,  117,  121,   65,  113,  122,   65,   95,  105,
      107,  108,  109,  116,  123,  117,  121,  130,   65,  122,
       65,   65,   65,   65,   65,  126,   91,  123,  124,   65,
       67,   67,   67,   67,  125,  124,  130,  125,  126,   67,
       86,  133,  125,  134,  125,  142,  135,   67,  128,  128,
      128,  128,  142,  128,  133,  137,  134,  128,   67,  135,
       67,   73,   73,   73,   73,  136,  138,  139,  137,  136,
      140,  141,  144,  152,  153,   73,   80,  154,   73,  138,
      139,  160,  146,  140,  141,  144,  152,  153,  160,   73,

      154,   73,   73,   73,   73,   73,  145,  145,  145,  145,
       73,   77,   77,   77,   77,  146,  143,  145,  149,  143,
      147,  147,  147,  147,  143,   77,  143,  155,   77,  178,
       75,  147,   74,   71,   69,   56,  178,  149,   53,   77,
      155,   77,   77,   77,   77,   77,  151,  151,  151,  151,
       77,  106,  106,  106,  106,  156,  106,  157,  158,  159,
      106,  162,  106,  151,  163,  163,  163,  163,  156,  164,
      157,  158,  159,  164,  162,  163,  151,  168,  166,  106,
      127,  127,  127,  127,  161,  127,  166,  161,  183,  127,
      168,  127,  161,  170,  161,   52,  164,   50,  169,  169,

      169,  169,  180,  172,  173,  166,  170,  183,  127,  132,
      132,  132,  132,   48,  132,  169,  172,  173,  132,  171,
      171,  171,  171,  175,  177,  180,  132,   46,  169,  174,
      174,  174,  174,  182,  184,  181,  175,  177,  189,  132,
      148,  148,  148,   44,  148,  189,  182,  171,  176,  176,
      176,  176,  185,  184,   40,  187,  148,  174,  181,   34,
      186,  186,  186,  186,   32,  185,  188,  148,  187,  148,
      150,  150,  150,   24,  190,  191,  176,  186,  150,  188,
      194,  192,  192,  192,  192,   23,  150,  190,  191,   20,
      186,  195,   19,  194,   18,   14,    9,  150,  192,  150,

      165,  165,  165,  165,  195,  165,  196,  196,  196,  196,
        0,  192,  197,  198,  200,    0,  201,  165,    0,    0,
        0,    0,    0,  196,    0,  197,  198,  200,  165,  201,
      165,  167,  167,  167,  167,    0,  196,    0,    0,    0,
      167,  199,  199,  199,  199,    0,    0,    0,  167,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  199,  167,
        0,  167,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  199,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  204,    0,  204,  204,  204,  204,  204,  204,  205,
      205,    0,  205,  206,    0,  206,  206,  206,  206,  206,

      206,  207,    0,    0,  207,  207,  207,  208,  208,  209,
      209,  209,    0,  209,  210,  210,  210,  210,  210,  210,
      210,  210,  210,  211,  211,    0,  211,  212,  212,    0,
      212,  213,  213,  213,  213,  213,  213,  213,  213,  213,
      214,  214,  214,  214,  214,  214,  214,  214,  214,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  217,  217,  217,
        0,  217,  217,  217,  217,  218,    0,  218,  218,  218,
      218,  218,  218,  219,    0,  219,  219,  219,  219,  219,
      219,  202,  202,  202,  202,  202,  202,  202,  202,  202,

      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "../../css.l"
#define INITIAL 0
#line 2 "../../css.l"

/* $Id: css.l,v 1.7 2001/07/02 19:43:43 owagner Exp $ */

#define YY_INPUT(b,r,m) r=my_yyinput(b,m)
static int my_yyinput(char *,int);

#define ECHO
#define YY_NEVER_INTERACTIVE 1
#define YY_NO_INPUT 1

#define YY_FATAL_ERROR(x) yyerror(x)

static void dummy( void ) { }
static int input( void );

#define fprintf(a,b,c) dummy()

#define YY_NO_INPUT 1
#define YY_NO_UNPUT 1
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#define YY_NO_SCAN_BUFFER 1
#define YY_NO_SCAN_BYTES 1
#define YY_NO_SCAN_STRING 1
#define COMMENT 1

#define DQUOTED 2

#define SQUOTED 3

#line 648 "css_scanner.h"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 48 "../../css.l"


#line 802 "css_scanner.h"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 203 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 202 );
		yy_cp = yy_last_accepting_cpos;
		yy_current_state = yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
#line 51 "../../css.l"
case 2:
#line 52 "../../css.l"
case 3:
YY_RULE_SETUP
#line 52 "../../css.l"
{/* HTML comment, skip*/}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 54 "../../css.l"
{ return CSSTOKEN_IDENT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "../../css.l"
{ return CSSTOKEN_ATKEYWORD; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 56 "../../css.l"
{ return CSSTOKEN_STRING; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "../../css.l"
{ return CSSTOKEN_HASH; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "../../css.l"
{ return CSSTOKEN_NUMBER; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 59 "../../css.l"
{ return CSSTOKEN_PERCENTAGE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 60 "../../css.l"
{ return CSSTOKEN_DIMENSION; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 61 "../../css.l"
{ return CSSTOKEN_URI; } 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "../../css.l"
{ return CSSTOKEN_UNICODE_RANGE; } 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "../../css.l"
{ return ';'; } 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "../../css.l"
{ return '{'; } 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 65 "../../css.l"
{ return '}'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 66 "../../css.l"
{ return '('; } 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 67 "../../css.l"
{ return ')'; } 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 68 "../../css.l"
{ return '['; } 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 69 "../../css.l"
{ return ']'; } 
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 70 "../../css.l"
{ return CSSTOKEN_S; } 
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 71 "../../css.l"
{ /* Eat comment */ } 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 72 "../../css.l"
{ return CSSTOKEN_FUNCTION; } 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 73 "../../css.l"
{ return CSSTOKEN_INCLUDES; } 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 74 "../../css.l"
{ return CSSTOKEN_DASHMATCH; } 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 75 "../../css.l"
{ return CSSTOKEN_DELIM; } 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 76 "../../css.l"
ECHO;
	YY_BREAK
#line 1005 "css_scanner.h"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(DQUOTED):
case YY_STATE_EOF(SQUOTED):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_last_accepting_cpos;
				yy_current_state = yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 203 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 203 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 202);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 76 "../../css.l"


static int my_yyinput( char *buf, int max ) 
{
    return( 0 );  
}

void csserror(char*msg)
{

}
